### PR TITLE
Use PowerShell 5 for Build + Test

### LINKED ISSUE #25: Use PowerShell 5 to Build and Test
### Problem description

I ran into the following issue which is resolved by using PS5.
microsoft/Microsoft365DSC#2054

### Verbose logs

```text
PowerShell 7 error: `Configuration: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".`
```

### How to reproduce

Manually compile the following.

```
Configuration MyConfig {

    Import-DscResource -ModuleName Microsoft365DSC

    Node localhost {

        TeamsClientConfiguration Config {
            Identity                         = 'Global'
            AllowBox                         = $true
            AllowDropBox                     = $true
            AllowEmailIntoChannel            = $true
            AllowGoogleDrive                 = $true
            AllowGuestUser                   = $true
            AllowOrganizationTab             = $true
            AllowResourceAccountSendMessage  = $true
            AllowScopedPeopleSearchandAccess = $true
            AllowShareFile                   = $true
            AllowSkypeBusinessInterop        = $true
            AllowEgnyte                      = $true
            ContentPin                       = "RequiredOutsideScheduleMeeting"
            ResourceAccountContentAccess     = "NoAccess"
        }
    }
}
```

### Expected behavior

Resource should compile

### Current behavior

Resource fails to compile

### Suggested solution

Move build and test pipeline to PS5.

### Operating system the target node is running

```text
N/A
```

### PowerShell version and build the target node is running

```text
N/A
```

### Module version used

```text
N/A
```

### PR DESCRIPTION
**Pull request by dan-hughes**
# Pull Request

### Changed
Build pipeline to use PowerShell 5. Some resources require this to compile.
Fixes #25 

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

### CODE REVIEW

**Comment by raandree** [comment]
Sorry for the late response, @dan-hughes. We build this with PowerShell 7 all the time. Which resources are filing in PowerShell 7?

**Comment by dan-hughes** [comment]
I have a PR sitting here for the Teams resources but ran into the issue referenced in the issue linked here.

The M365 DscResource will not compile with PS7. Hence the need to switch to PS5.

**Comment by raandree** [comment]
I don't see a branch in your fork with changes regarding Teams. Can you create it so I can take a look, please?

**Comment by dan-hughes** [comment]
I've just built and compiled with the latest M365Dsc module and it looks like this is fixed now and this is not required. I'll draft a PR for the Teams resources, as it was based on an older module version.

**Comment by dan-hughes** [comment]
This does not look to be an issue now. Everything builds and tests in PS7.

**Comment by dan-hughes** [comment]
This does not look to be an required now. Everything builds and tests in PS7.

**Pull request closed without merging**
